server:
  port: 8080
  servlet:
    context-path: /truckrobot

spring:
  application:
    name: truck-robot-api

logging:
  level:
    com.example.truckrobot: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info